#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 square
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 geohash
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0
##java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 square
##sleep 60
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 1000 geohash
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 1000
##java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 1000 square
##java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 0 square
##sleep 60
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 square
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 geohash
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0
##java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 square
##sleep 60
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0
##java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 square
#sleep 60
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 square

#sleep 60
# 20m
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 pointyTriangle

# 20m
#echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 1000 1 0 pointyTriangle
#echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 2000 1 0 pointyTriangle
#echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 3000 1 0 pointyTriangle
#echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 4000 1 0 pointyTriangle
#echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 pointyTriangle
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m safegraph20m_extents_1k.txt 5000 1 0 pointyTriangle
