# echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m 1 1000 ./safegraph10m_extents_1k.txt 0 ./safegraph5m_fs_output-1000.txt
# java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m 1 1000 ./safegraph10m_extents_1k.txt 0 ./safegraph5m_fs_output-1000.txt
# echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m_1 1 1000 ./safegraph10m_extents_1k.txt 0 ./safegraph10m_fs_output-1000.txt
# java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m_1 1 1000 ./safegraph10m_extents_1k.txt 0 ./safegraph10m_fs_output-1000.txt
#
echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m 1 1000 ./safegraph20m_extents_1k.txt 0 ./safegraph20m_fs_output-1000.txt
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph20m 1 1000 ./safegraph20m_extents_1k.txt 0 ./safegraph20m_fs_output-1000.txt
#
echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph50m 1 1000 ./safegraph50m_extents_1k.txt 0 ./safegraph50m_fs_output-1000.txt
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m_1 1 1000 ./safegraph50m_extents_1k.txt 0 ./safegraph50m_fs_output-1000.txt
#
echo java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph100m 1 1000 ./safegraph100m_extents_1k.txt 0 ./safegraph100m_fs_output-1000.txt
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.FeatureServiceConcurrentTester2 https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph100m 1 1000 ./safegraph100m_extents_1k.txt 0 ./safegraph100m_fs_output-1000.txt
