java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 5000 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 5000 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 5000 0
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 5000 0 square
#sleep 60
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 4000 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 4000 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 4000 0
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 4000 0 square
#sleep 60
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 3000 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 3000 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 3000 0
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 3000 0 square
#sleep 60
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 2000 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 2000 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 2000 0
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 2000 0 square
#sleep 60
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 1000 0 square
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 1000 0 geohash
java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 1000 0
#java -cp ./target/ms-fs-performance-test-1.0-jar-with-dependencies.jar com.esri.arcgis.performance.test.mat.MapServiceRandomAggTester https://us-iotdev.arcgis.com/devlion/cqvgkj9zrnkn9bcu/maps/arcgis/rest/services/ safegraph5m safegraph5m_extents_1k.txt 1000 0 square
#sleep 60

